apiVersion: v1
kind: Service
metadata:
  name: {{ include "pixelpromo.fullname" . }}
  labels:
    {{- include "pixelpromo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "pixelpromo.selectorLabels" . | nindent 4 }}
