wordpress:
  wordpressUsername: admin
  wordpressPassword: your-secure-password
  
  service:
    type: ClusterIP
    port: 80
    
  # Configure Ingress for Traefik
  ingress:
    enabled: true
    ingressClassName: "traefik"
    hostname: dev.lightningspore.com
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.priority: "100"
    tls: true
    # extraTls:
    #   - hosts:
    #       - dev.lightningspore.com
    #     secretName: dev.lightningspore.com-tls
    
  persistence:
    enabled: true
    size: 5Gi
    
  resources:
    limits:
      cpu: 2000m
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 512Mi

  mariadb:
    auth:
      rootPassword: mysql-root-password
      database: bitnami_wordpress
      username: bn_wordpress
      password: mysql-user-password
    
    primary:
      persistence:
        enabled: true
        size: 5Gi

    resources:
      requests:
        cpu: 1000m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 1024Mi