wordpress:
  wordpressUsername: admin
  wordpressPassword: your-secure-password
  wordpressEmail: admin@example.com
  wordpressFirstName: Admin
  wordpressLastName: User
  wordpressBlogName: My Blog
  
  # Change service type to ClusterIP (default)
  service:
    type: ClusterIP
    port: 80
    
  # Configure Ingress for Traefik
  ingress:
    enabled: true
    ingressClassName: "traefik"
    hostname: dev.lightningspore.com
    annotations:
      cert-manager.io/issuer: "letsencrypt-prod"
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
      traefik.ingress.kubernetes.io/router.priority: "100"
    tls: false
    extraTls:
      - hosts:
          - dev.lightningspore.com
        secretName: dev.lightningspore.com-tls

    # enabled: true
    # className: "traefik"
    # annotations:
    #   cert-manager.io/issuer: "letsencrypt-prod"
    # hosts:
    #   - host: lnbits.lightningspore.com
    #     paths:
    #       - path: /
    #         pathType: Prefix
    # tls:
    # - secretName: lnbits-lightningspore-tls
    #   hosts:
    #     - lnbits.lightningspore.com

    
  persistence:
    enabled: true
    size: 5Gi
    
  resources:
    limits:
      cpu: 2000m
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 512Mi

mysql:
  auth:
    rootPassword: mysql-root-password
    database: bitnami_wordpress
    username: bn_wordpress
    password: mysql-user-password
  
  primary:
    persistence:
      enabled: true
      size: 5Gi