---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        instance: home
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake
  labels:
    app: snake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake
  template:
    metadata:
      labels:
        app: snake
    spec:
      nodeSelector:
        instance: home
      containers:
      - name: snake
        image: public.ecr.aws/i9m8a4n0/cycle-snake:latest
        ports:
        - containerPort: 3000
          name: app
---
apiVersion: v1
kind: Service
metadata:
  name: snake-service
spec:
  selector:
    app: snake  # Assuming your snake pod has a label app=snake
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000  # Adjust this to the port your snake pod listens on
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: label
  labels:
    app: label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label
  template:
    metadata:
      labels:
        app: label
    spec:
      nodeSelector:
        instance: home
      containers:
      - name: label
        image: 190928636648.dkr.ecr.us-west-2.amazonaws.com/label-printer:latest
        ports:
        - containerPort: 8080
          name: app
        volumeMounts:
        - name: usb-lp0
          mountPath: /dev/usb/lp0
        securityContext:
          privileged: true
      imagePullSecrets:
      - name: aws-registry

      volumes:
      - name: usb-lp0
        hostPath:
          path: /dev/usb/lp0
          type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: label-service
spec:
  selector:
    app: label
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080  # Adjust this to the port your snake pod listens on
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  # annotations:
  #   cert-manager.io/issuer: "letsencrypt-staging"
spec:
  ingressClassName: "traefik"
  # tls:
  # - hosts:
  #   - samkorn.xyz
  #   - samkorn.me
  #   secretName: xyz-app-tls
  rules:
  - host: samkorn.xyz
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  - host: samkorn.me
    http:
      paths:         
      - path: /
        pathType: Prefix
        backend:
          service:
            name: snake-service
            port:
              number: 3000
  - host: samkorn.xyz
    http:
      paths:         
      - path: /
        pathType: Prefix
        backend:
          service:
            name: label-service
            port:
              number: 8080
