apiVersion: batch/v1
kind: CronJob
metadata:
  name: aws-registry-credential-cron
spec:
  # schedule: "0 */4 * * *"
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2  
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          serviceAccountName: ecr-token-updater
          restartPolicy: Never
          # Run on the AWS instance since it has an instanceprofile with the proper role attached
          nodeSelector:
            instance: internal
          dnsPolicy: "ClusterFirst"
          dnsConfig:
            nameservers:
              - "8.8.8.8"
              - "169.254.169.253"
          containers:
          - name: kubectl
            imagePullPolicy: Always
            image: public.ecr.aws/i9m8a4n0/aws-kubectl:latest
            command:
            - "/bin/sh"
            - "-c"
            - |
              AWS_REGION=us-west-2
              DOCKER_REGISTRY_SERVER=https://190928636648.dkr.ecr.${AWS_REGION}.amazonaws.com
              DOCKER_USER=AWS
              DOCKER_PASSWORD=$(aws ecr get-login-password --region ${AWS_REGION})
              
              # Update default namespace
              kubectl delete secret aws-registry -n default || true
              kubectl create secret docker-registry aws-registry -n default \
              --docker-server=$DOCKER_REGISTRY_SERVER \
              --docker-username=$DOCKER_USER \
              --docker-password=$DOCKER_PASSWORD \
              --docker-email=no@email.local
              kubectl patch serviceaccount default -n default -p '{"imagePullSecrets":[{"name":"aws-registry"}]}'
              
              # Update lnspore namespace
              kubectl delete secret aws-registry -n lnspore || true
              kubectl create secret docker-registry aws-registry -n lnspore \
              --docker-server=$DOCKER_REGISTRY_SERVER \
              --docker-username=$DOCKER_USER \
              --docker-password=$DOCKER_PASSWORD \
              --docker-email=no@email.local
              kubectl patch serviceaccount default -n lnspore -p '{"imagePullSecrets":[{"name":"aws-registry"}]}'
              
              # Update kornpow namespace
              kubectl delete secret aws-registry -n kornpow || true
              kubectl create secret docker-registry aws-registry -n kornpow \
              --docker-server=$DOCKER_REGISTRY_SERVER \
              --docker-username=$DOCKER_USER \
              --docker-password=$DOCKER_PASSWORD \
              --docker-email=no@email.local
              kubectl patch serviceaccount default -n kornpow -p '{"imagePullSecrets":[{"name":"aws-registry"}]}'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: ecr-token-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: secret-updater-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete", "patch", "get", "list"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lnspore
  name: secret-updater-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete", "patch", "get", "list"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kornpow
  name: secret-updater-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete", "patch", "get", "list"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-updater-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: ecr-token-updater
  namespace: default
roleRef:
  kind: Role
  name: secret-updater-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-updater-rolebinding
  namespace: lnspore
subjects:
- kind: ServiceAccount
  name: ecr-token-updater
  namespace: default
roleRef:
  kind: Role
  name: secret-updater-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-updater-rolebinding
  namespace: kornpow
subjects:
- kind: ServiceAccount
  name: ecr-token-updater
  namespace: default
roleRef:
  kind: Role
  name: secret-updater-role
  apiGroup: rbac.authorization.k8s.io