apiVersion: v1
kind: Pod
metadata:
  name: test-ecr-updater
spec:
  containers:
  - name: ecr-test
    image: ubuntu:latest
    # image: public.ecr.aws/i9m8a4n0/aws-kubectl:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    command:
    - "sleep"
    - "infinity"
  nodeSelector:
    instance: internal
