apiVersion: v1
kind: Service
metadata:
  name: {{ include "resume.fullname" . }}
  labels:
    {{- include "resume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "resume.selectorLabels" . | nindent 4 }}
