apiVersion: v1
kind: Service
metadata:
  name: {{ include "lnbits.fullname" . }}
  labels:
    {{- include "lnbits.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    {{- include "lnbits.selectorLabels" . | nindent 4 }}
