apiVersion: v1
kind: Service
metadata:
  name: {{ include "coracle.fullname" . }}
  labels:
    {{- include "coracle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "coracle.selectorLabels" . | nindent 4 }}
